#include "dos.h"


void set_abort_routine(void *routine) __naked __z88dk_fastcall
{
	routine;

#ifdef MSXDOS2
/*
    DEFINE ABORT EXIT ROUTINE (63H)
    Parameters:    C = 63H (_DEFAB) 
                  DE = Address of abort exit routine 
                       0000H to un-define routine 
    Results:       A = 0 (never generates errors)

This function is only available when called via location 00005h in the MSX-DOS
environment. It cannot be called at location 0F37Dh from the disk BASIC
environment.

If register DE is zero then a previously defined abort routine will be
undefined, otherwise a new one will be defined. The abort routine will be
called by the system whenever the transient program is about to terminate for
any reason other than a direct jump to location 0000h. Programs written for
MSX-DOS 2 should exit with a "terminate with error code" function call
(function 061h) rather than a jump to location 0000h.

The user abort routine will be entered with the user stack active, with IX, IY
and the alternate register set as it was when the function call was made and
with the whole TPA paged in. The termination error code will be passed to the
routine in register A with a secondary error code in register B and if the
routine executes a "RET" then the values returned in registers A and B will be
stored as the error codes to be returned by the "join" function, and normally
printed out by the command interpreter. Alternatively the routine may jump to
some warm start code in the transient program rather than returning. The system
will be in a perfectly stable state able to accept any function calls.

The primary error code passed to the routine in register A will be the code
which the program itself passed to the "terminate with error code" function
(which may be zero) if this is the reason for the termination. The routine will
also be called if a Ctrl-C or Ctrl-STOP is detected (".CTRLC" or ".STOP"
error), if a disk error is aborted (".ABORT" error), or if an error occurred on
one of the standard input or output channels being accessed through MSX-DOS
function calls 01h...0Bh (".INERR" or ".OUTERR").

The errors ".ABORT", ".INERR" and ".OUTERR" are generated by the system as a
result of some other error. For example a ".ABORT" can result from a ".NRDY"
error, or a ".INERR" can result from a ".EOF" error. In these cases the
original error code (".NRDY" or ".EOF") is passed to the abort routine in
register B as the secondary error code. For all other errors there is no
secondary error code and register B will be zero.

If the abort routine executes "POP HL : RET" (or equivalent) rather than a
simple return, then control will pass to the instruction immediately following
the MSX-DOS call or BIOS call in which the error occurred. This may be useful
in conjunction with a disk error handler routine (see function 64h) to allow an
option to abort the current MSX-DOS call when a disk error occurs.
*/
	__asm
		ex de,hl

		ld c,#DEFAB
		DOSCALL

		ret
	__endasm;
#endif

#ifdef MSXDOS1
	__asm__ ("ret");
#endif
}
